name: hangman_game
description: "hangman_game is a complete result of noklachia moment felt during
  work about good old childhood games."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_icon: ^0.0.9
  audioplayers: ^6.0.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  pushable_button: ^0.0.4
  shared_preferences: null
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/loaders/
    - assets/buttons/
    - assets/audio/
    - assets/gifs/
