name: hangman_game
description: "hangman_game is a complete result of noklachia moment felt during work about good old childhood games."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  gap: ^3.0.1
  get: ^4.6.6
  lottie: ^3.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/loaders/
    - assets/buttons/
    - assets/audio/
